version: '2'

services:
  backend:
    build: .
    ports:
      - "4000:4000"
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    environment:
      PORT: 4000