version: '2'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    env_file:
      .env

  backend:
    build: .
    depends_on:
      - postgres
    ports:
      - 4000:4000
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:docker
    env_file:
      - .env